global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']  # Target Prometheus service itself
  - job_name: 'node'
    static_configs:
      - targets: ['node_exporter:9100']  # Target Node Exporter service
